#!/bin/bash

L=1

while :
do
    ./testdriver test_data/big_test.txt 2> err.txt > out.txt
    sort err.txt > log/doc6562.txt
    diff log/doc6562.txt log/doc6562_sorted_unique.txt > log/diff.txt

    if [ $? -ne 0 ]
    then
        echo "Problem in loop" $L ":("
        break
    fi

    echo "Loop" $L "OK"
    L=$[L+1]
done
